import { RoomTemplate } from './types';

export const furnitureLibrary = [
  { type: 'sofa-3seat', name: 'Диван 3-местный', width: 200, height: 90, color: '#8B5CF6', icon: 'RectangleHorizontal', category: 'living' },
  { type: 'sofa-2seat', name: 'Диван 2-местный', width: 160, height: 90, color: '#7E69AB', icon: 'RectangleHorizontal', category: 'living' },
  { type: 'sofa-corner', name: 'Угловой диван', width: 240, height: 180, color: '#9b87f5', icon: 'RectangleHorizontal', category: 'living' },
  { type: 'armchair', name: 'Кресло', width: 80, height: 80, color: '#8B5CF6', icon: 'Square', category: 'living' },
  { type: 'armchair-rocking', name: 'Кресло-качалка', width: 70, height: 90, color: '#9b87f5', icon: 'Square', category: 'living' },
  { type: 'ottoman', name: 'Пуф', width: 50, height: 50, color: '#D6BCFA', icon: 'Square', category: 'living' },
  { type: 'bench', name: 'Скамья', width: 120, height: 40, color: '#7E69AB', icon: 'RectangleHorizontal', category: 'living' },
  
  { type: 'coffee-table', name: 'Журнальный столик', width: 100, height: 60, color: '#92400E', icon: 'RectangleHorizontal', category: 'living' },
  { type: 'side-table', name: 'Приставной столик', width: 50, height: 50, color: '#A16207', icon: 'Square', category: 'living' },
  { type: 'console-table', name: 'Консоль', width: 120, height: 35, color: '#92400E', icon: 'RectangleHorizontal', category: 'living' },
  { type: 'tv-stand', name: 'ТВ-тумба', width: 180, height: 50, color: '#1A1F2C', icon: 'RectangleHorizontal', category: 'living' },
  { type: 'tv-stand-large', name: 'ТВ-тумба большая', width: 200, height: 50, color: '#1A1F2C', icon: 'RectangleHorizontal', category: 'living' },
  { type: 'bookshelf', name: 'Книжный шкаф', width: 80, height: 40, color: '#1A1F2C', icon: 'RectangleHorizontal', category: 'living' },
  { type: 'bookshelf-tall', name: 'Стеллаж высокий', width: 120, height: 40, color: '#1E293B', icon: 'RectangleHorizontal', category: 'living' },
  { type: 'display-cabinet', name: 'Витрина', width: 100, height: 45, color: '#334155', icon: 'RectangleHorizontal', category: 'living' },
  
  { type: 'bed-single', name: 'Односпальная кровать', width: 90, height: 200, color: '#6E59A5', icon: 'RectangleVertical', category: 'bedroom' },
  { type: 'bed-double', name: 'Двуспальная кровать', width: 140, height: 200, color: '#7E69AB', icon: 'RectangleVertical', category: 'bedroom' },
  { type: 'bed-queen', name: 'Кровать Queen', width: 160, height: 200, color: '#8B5CF6', icon: 'RectangleVertical', category: 'bedroom' },
  { type: 'bed-king', name: 'Кровать King', width: 180, height: 200, color: '#9b87f5', icon: 'RectangleVertical', category: 'bedroom' },
  { type: 'bunk-bed', name: 'Двухъярусная кровать', width: 100, height: 200, color: '#6E59A5', icon: 'RectangleVertical', category: 'bedroom' },
  { type: 'nightstand', name: 'Прикроватная тумба', width: 40, height: 40, color: '#92400E', icon: 'Square', category: 'bedroom' },
  { type: 'dresser', name: 'Комод', width: 120, height: 50, color: '#A16207', icon: 'RectangleHorizontal', category: 'bedroom' },
  { type: 'dresser-tall', name: 'Комод высокий', width: 80, height: 50, color: '#92400E', icon: 'RectangleHorizontal', category: 'bedroom' },
  { type: 'wardrobe-single', name: 'Шкаф 1-дверный', width: 60, height: 60, color: '#1A1F2C', icon: 'RectangleHorizontal', category: 'bedroom' },
  { type: 'wardrobe-double', name: 'Шкаф 2-дверный', width: 100, height: 60, color: '#1E293B', icon: 'RectangleHorizontal', category: 'bedroom' },
  { type: 'wardrobe-triple', name: 'Шкаф 3-дверный', width: 150, height: 60, color: '#334155', icon: 'RectangleHorizontal', category: 'bedroom' },
  { type: 'wardrobe-corner', name: 'Угловой шкаф', width: 100, height: 100, color: '#1A1F2C', icon: 'Square', category: 'bedroom' },
  { type: 'vanity', name: 'Туалетный столик', width: 100, height: 50, color: '#D6BCFA', icon: 'RectangleHorizontal', category: 'bedroom' },
  { type: 'mirror-floor', name: 'Напольное зеркало', width: 60, height: 20, color: '#CBD5E1', icon: 'RectangleHorizontal', category: 'bedroom' },
  
  { type: 'dining-table-4', name: 'Обеденный стол (4 места)', width: 120, height: 80, color: '#92400E', icon: 'RectangleHorizontal', category: 'dining' },
  { type: 'dining-table-6', name: 'Обеденный стол (6 мест)', width: 160, height: 90, color: '#A16207', icon: 'RectangleHorizontal', category: 'dining' },
  { type: 'dining-table-8', name: 'Обеденный стол (8 мест)', width: 200, height: 100, color: '#92400E', icon: 'RectangleHorizontal', category: 'dining' },
  { type: 'dining-table-round', name: 'Круглый стол', width: 120, height: 120, color: '#A16207', icon: 'Circle', category: 'dining' },
  { type: 'dining-chair', name: 'Обеденный стул', width: 45, height: 45, color: '#7E69AB', icon: 'Square', category: 'dining' },
  { type: 'dining-chair-arm', name: 'Стул с подлокотниками', width: 50, height: 50, color: '#8B5CF6', icon: 'Square', category: 'dining' },
  { type: 'bar-stool', name: 'Барный стул', width: 40, height: 40, color: '#6E59A5', icon: 'Square', category: 'dining' },
  { type: 'buffet', name: 'Сервант', width: 160, height: 50, color: '#1A1F2C', icon: 'RectangleHorizontal', category: 'dining' },
  { type: 'china-cabinet', name: 'Буфет', width: 120, height: 45, color: '#1E293B', icon: 'RectangleHorizontal', category: 'dining' },
  { type: 'bar-cart', name: 'Сервировочная тележка', width: 80, height: 45, color: '#334155', icon: 'RectangleHorizontal', category: 'dining' },
  
  { type: 'kitchen-counter', name: 'Кухонная столешница', width: 60, height: 60, color: '#64748B', icon: 'RectangleHorizontal', category: 'kitchen' },
  { type: 'kitchen-island', name: 'Кухонный остров', width: 120, height: 80, color: '#475569', icon: 'RectangleHorizontal', category: 'kitchen' },
  { type: 'refrigerator', name: 'Холодильник', width: 60, height: 70, color: '#E2E8F0', icon: 'RectangleHorizontal', category: 'kitchen' },
  { type: 'refrigerator-french', name: 'Холодильник French Door', width: 90, height: 70, color: '#CBD5E1', icon: 'RectangleHorizontal', category: 'kitchen' },
  { type: 'stove', name: 'Плита', width: 60, height: 60, color: '#1E293B', icon: 'Square', category: 'kitchen' },
  { type: 'dishwasher', name: 'Посудомоечная машина', width: 60, height: 60, color: '#CBD5E1', icon: 'Square', category: 'kitchen' },
  { type: 'microwave', name: 'Микроволновка', width: 50, height: 40, color: '#94A3B8', icon: 'RectangleHorizontal', category: 'kitchen' },
  { type: 'sink-single', name: 'Раковина одинарная', width: 60, height: 50, color: '#CBD5E1', icon: 'RectangleHorizontal', category: 'kitchen' },
  { type: 'sink-double', name: 'Раковина двойная', width: 90, height: 50, color: '#CBD5E1', icon: 'RectangleHorizontal', category: 'kitchen' },
  { type: 'kitchen-cabinet', name: 'Кухонный шкаф', width: 60, height: 35, color: '#1A1F2C', icon: 'RectangleHorizontal', category: 'kitchen' },
  { type: 'pantry', name: 'Кладовая', width: 80, height: 50, color: '#334155', icon: 'RectangleHorizontal', category: 'kitchen' },
  
  { type: 'desk', name: 'Письменный стол', width: 120, height: 60, color: '#92400E', icon: 'RectangleHorizontal', category: 'office' },
  { type: 'desk-corner', name: 'Угловой стол', width: 140, height: 140, color: '#A16207', icon: 'Square', category: 'office' },
  { type: 'desk-standing', name: 'Стол стоя-сидя', width: 140, height: 70, color: '#92400E', icon: 'RectangleHorizontal', category: 'office' },
  { type: 'office-chair', name: 'Офисное кресло', width: 60, height: 60, color: '#1E293B', icon: 'Square', category: 'office' },
  { type: 'desk-chair', name: 'Рабочий стул', width: 50, height: 50, color: '#334155', icon: 'Square', category: 'office' },
  { type: 'filing-cabinet', name: 'Картотечный шкаф', width: 45, height: 60, color: '#64748B', icon: 'RectangleHorizontal', category: 'office' },
  { type: 'bookcase', name: 'Книжный шкаф', width: 80, height: 30, color: '#1A1F2C', icon: 'RectangleHorizontal', category: 'office' },
  { type: 'credenza', name: 'Креденца', width: 150, height: 50, color: '#1E293B', icon: 'RectangleHorizontal', category: 'office' },
  { type: 'conference-table', name: 'Конференц-стол', width: 240, height: 120, color: '#92400E', icon: 'RectangleHorizontal', category: 'office' },
  { type: 'whiteboard', name: 'Доска', width: 120, height: 10, color: '#F1F5F9', icon: 'RectangleHorizontal', category: 'office' },
  
  { type: 'bathtub', name: 'Ванна', width: 170, height: 80, color: '#F1F5F9', icon: 'RectangleVertical', category: 'bathroom' },
  { type: 'bathtub-corner', name: 'Угловая ванна', width: 140, height: 140, color: '#E2E8F0', icon: 'Square', category: 'bathroom' },
  { type: 'shower', name: 'Душевая кабина', width: 90, height: 90, color: '#CBD5E1', icon: 'Square', category: 'bathroom' },
  { type: 'toilet', name: 'Унитаз', width: 40, height: 60, color: '#F1F5F9', icon: 'RectangleVertical', category: 'bathroom' },
  { type: 'bidet', name: 'Биде', width: 40, height: 55, color: '#F1F5F9', icon: 'RectangleVertical', category: 'bathroom' },
  { type: 'bathroom-sink', name: 'Раковина', width: 50, height: 45, color: '#F1F5F9', icon: 'RectangleHorizontal', category: 'bathroom' },
  { type: 'bathroom-vanity', name: 'Тумба с раковиной', width: 100, height: 50, color: '#1A1F2C', icon: 'RectangleHorizontal', category: 'bathroom' },
  { type: 'bathroom-vanity-double', name: 'Двойная тумба', width: 150, height: 50, color: '#1E293B', icon: 'RectangleHorizontal', category: 'bathroom' },
  { type: 'linen-cabinet', name: 'Шкаф для белья', width: 60, height: 40, color: '#334155', icon: 'RectangleHorizontal', category: 'bathroom' },
  { type: 'bathroom-mirror', name: 'Зеркало', width: 80, height: 10, color: '#CBD5E1', icon: 'RectangleHorizontal', category: 'bathroom' },
  
  { type: 'plant-small', name: 'Растение маленькое', width: 25, height: 25, color: '#22C55E', icon: 'Circle', category: 'decor' },
  { type: 'plant-medium', name: 'Растение среднее', width: 35, height: 35, color: '#16A34A', icon: 'Circle', category: 'decor' },
  { type: 'plant-large', name: 'Растение большое', width: 50, height: 50, color: '#15803D', icon: 'Circle', category: 'decor' },
  { type: 'plant-floor', name: 'Напольное растение', width: 60, height: 60, color: '#166534', icon: 'Circle', category: 'decor' },
  { type: 'plant-tree', name: 'Дерево в горшке', width: 70, height: 70, color: '#14532D', icon: 'Circle', category: 'decor' },
  { type: 'vase', name: 'Ваза', width: 20, height: 20, color: '#F59E0B', icon: 'Circle', category: 'decor' },
  { type: 'sculpture', name: 'Скульптура', width: 30, height: 30, color: '#64748B', icon: 'Circle', category: 'decor' },
  { type: 'floor-lamp', name: 'Торшер', width: 30, height: 30, color: '#FEF7CD', icon: 'Circle', category: 'decor' },
  { type: 'table-lamp', name: 'Настольная лампа', width: 20, height: 20, color: '#FDE1D3', icon: 'Circle', category: 'decor' },
  { type: 'pendant-light', name: 'Подвесной светильник', width: 40, height: 40, color: '#FBBF24', icon: 'Circle', category: 'decor' },
  { type: 'chandelier', name: 'Люстра', width: 60, height: 60, color: '#F59E0B', icon: 'Circle', category: 'decor' },
  { type: 'wall-art', name: 'Картина', width: 80, height: 10, color: '#8B5CF6', icon: 'RectangleHorizontal', category: 'decor' },
  { type: 'wall-art-large', name: 'Картина большая', width: 120, height: 10, color: '#7E69AB', icon: 'RectangleHorizontal', category: 'decor' },
  { type: 'mirror-wall', name: 'Настенное зеркало', width: 60, height: 10, color: '#CBD5E1', icon: 'RectangleHorizontal', category: 'decor' },
  { type: 'clock', name: 'Часы', width: 40, height: 40, color: '#1E293B', icon: 'Circle', category: 'decor' },
  { type: 'rug-small', name: 'Ковер маленький', width: 120, height: 90, color: '#DC2626', icon: 'RectangleHorizontal', category: 'decor' },
  { type: 'rug-medium', name: 'Ковер средний', width: 160, height: 120, color: '#B91C1C', icon: 'RectangleHorizontal', category: 'decor' },
  { type: 'rug-large', name: 'Ковер большой', width: 200, height: 150, color: '#991B1B', icon: 'RectangleHorizontal', category: 'decor' },
  { type: 'cushion', name: 'Подушка', width: 30, height: 30, color: '#E5DEFF', icon: 'Square', category: 'decor' },
  { type: 'throw', name: 'Плед', width: 40, height: 30, color: '#D6BCFA', icon: 'RectangleHorizontal', category: 'decor' },
  { type: 'curtains', name: 'Шторы', width: 100, height: 10, color: '#E2E8F0', icon: 'RectangleHorizontal', category: 'decor' },
  { type: 'blinds', name: 'Жалюзи', width: 80, height: 10, color: '#CBD5E1', icon: 'RectangleHorizontal', category: 'decor' },
  
  { type: 'treadmill', name: 'Беговая дорожка', width: 180, height: 80, color: '#1E293B', icon: 'RectangleVertical', category: 'sports' },
  { type: 'exercise-bike', name: 'Велотренажер', width: 60, height: 80, color: '#334155', icon: 'RectangleHorizontal', category: 'sports' },
  { type: 'weight-bench', name: 'Скамья для жима', width: 140, height: 60, color: '#475569', icon: 'RectangleVertical', category: 'sports' },
  { type: 'yoga-mat', name: 'Коврик для йоги', width: 60, height: 180, color: '#8B5CF6', icon: 'RectangleVertical', category: 'sports' },
  { type: 'punching-bag', name: 'Боксерская груша', width: 40, height: 40, color: '#DC2626', icon: 'Circle', category: 'sports' },
  
  { type: 'piano', name: 'Пианино', width: 150, height: 60, color: '#1A1F2C', icon: 'RectangleHorizontal', category: 'entertainment' },
  { type: 'guitar-stand', name: 'Гитарная стойка', width: 30, height: 50, color: '#92400E', icon: 'RectangleHorizontal', category: 'entertainment' },
  { type: 'pool-table', name: 'Бильярдный стол', width: 230, height: 130, color: '#16A34A', icon: 'RectangleHorizontal', category: 'entertainment' },
  { type: 'foosball', name: 'Настольный футбол', width: 140, height: 80, color: '#92400E', icon: 'RectangleHorizontal', category: 'entertainment' },
  { type: 'arcade-machine', name: 'Игровой автомат', width: 70, height: 70, color: '#DC2626', icon: 'RectangleHorizontal', category: 'entertainment' },
  { type: 'gaming-chair', name: 'Игровое кресло', width: 70, height: 70, color: '#DC2626', icon: 'Square', category: 'entertainment' },
  
  { type: 'cradle', name: 'Колыбель', width: 90, height: 60, color: '#F1F5F9', icon: 'RectangleHorizontal', category: 'kids' },
  { type: 'crib', name: 'Детская кроватка', width: 130, height: 70, color: '#E2E8F0', icon: 'RectangleVertical', category: 'kids' },
  { type: 'changing-table', name: 'Пеленальный столик', width: 80, height: 50, color: '#CBD5E1', icon: 'RectangleHorizontal', category: 'kids' },
  { type: 'toy-chest', name: 'Ящик для игрушек', width: 90, height: 50, color: '#FBBF24', icon: 'RectangleHorizontal', category: 'kids' },
  { type: 'kids-desk', name: 'Детский стол', width: 90, height: 60, color: '#60A5FA', icon: 'RectangleHorizontal', category: 'kids' },
  { type: 'kids-chair', name: 'Детский стул', width: 35, height: 35, color: '#F87171', icon: 'Square', category: 'kids' },
  { type: 'rocking-horse', name: 'Лошадка-качалка', width: 80, height: 40, color: '#92400E', icon: 'RectangleHorizontal', category: 'kids' },
  { type: 'kids-bookshelf', name: 'Детская полка', width: 80, height: 30, color: '#8B5CF6', icon: 'RectangleHorizontal', category: 'kids' },
  
  { type: 'patio-chair', name: 'Садовое кресло', width: 60, height: 60, color: '#059669', icon: 'Square', category: 'outdoor' },
  { type: 'patio-table', name: 'Садовый стол', width: 120, height: 80, color: '#047857', icon: 'RectangleHorizontal', category: 'outdoor' },
  { type: 'sun-lounger', name: 'Шезлонг', width: 200, height: 70, color: '#10B981', icon: 'RectangleVertical', category: 'outdoor' },
  { type: 'hammock', name: 'Гамак', width: 140, height: 100, color: '#34D399', icon: 'RectangleHorizontal', category: 'outdoor' },
  { type: 'umbrella', name: 'Зонт', width: 80, height: 80, color: '#F97316', icon: 'Circle', category: 'outdoor' },
  { type: 'planter-large', name: 'Большое кашпо', width: 60, height: 60, color: '#92400E', icon: 'Square', category: 'outdoor' },
  { type: 'grill', name: 'Гриль', width: 80, height: 60, color: '#1E293B', icon: 'RectangleHorizontal', category: 'outdoor' },
  { type: 'fire-pit', name: 'Костровая чаша', width: 90, height: 90, color: '#EA580C', icon: 'Circle', category: 'outdoor' },
  
  { type: 'washer', name: 'Стиральная машина', width: 60, height: 60, color: '#E2E8F0', icon: 'Square', category: 'laundry' },
  { type: 'dryer', name: 'Сушильная машина', width: 60, height: 60, color: '#CBD5E1', icon: 'Square', category: 'laundry' },
  { type: 'ironing-board', name: 'Гладильная доска', width: 120, height: 40, color: '#94A3B8', icon: 'RectangleHorizontal', category: 'laundry' },
  { type: 'utility-sink', name: 'Раковина хозяйственная', width: 60, height: 50, color: '#F1F5F9', icon: 'RectangleHorizontal', category: 'laundry' },
  { type: 'storage-cabinet', name: 'Хозяйственный шкаф', width: 80, height: 40, color: '#64748B', icon: 'RectangleHorizontal', category: 'laundry' },
  
  { type: 'wine-rack', name: 'Винная полка', width: 60, height: 40, color: '#92400E', icon: 'RectangleHorizontal', category: 'storage' },
  { type: 'shoe-rack', name: 'Обувница', width: 80, height: 30, color: '#334155', icon: 'RectangleHorizontal', category: 'storage' },
  { type: 'coat-rack', name: 'Вешалка', width: 40, height: 40, color: '#1E293B', icon: 'Square', category: 'storage' },
  { type: 'umbrella-stand', name: 'Подставка для зонтов', width: 30, height: 30, color: '#475569', icon: 'Circle', category: 'storage' },
  { type: 'magazine-rack', name: 'Журнальница', width: 40, height: 30, color: '#64748B', icon: 'RectangleHorizontal', category: 'storage' },
  { type: 'storage-bench', name: 'Скамья с ящиком', width: 120, height: 45, color: '#92400E', icon: 'RectangleHorizontal', category: 'storage' },
  { type: 'trunk', name: 'Сундук', width: 100, height: 50, color: '#A16207', icon: 'RectangleHorizontal', category: 'storage' },
  { type: 'ladder-shelf', name: 'Полка-лестница', width: 60, height: 40, color: '#1A1F2C', icon: 'RectangleHorizontal', category: 'storage' },
  { type: 'cube-storage', name: 'Кубический стеллаж', width: 100, height: 100, color: '#334155', icon: 'Square', category: 'storage' },
  { type: 'floating-shelf', name: 'Навесная полка', width: 80, height: 10, color: '#475569', icon: 'RectangleHorizontal', category: 'storage' },
  
  { type: 'desk-organizer', name: 'Органайзер', width: 30, height: 20, color: '#64748B', icon: 'RectangleHorizontal', category: 'accessories' },
  { type: 'wastebasket', name: 'Корзина для мусора', width: 25, height: 25, color: '#94A3B8', icon: 'Circle', category: 'accessories' },
  { type: 'laundry-basket', name: 'Корзина для белья', width: 40, height: 40, color: '#CBD5E1', icon: 'Square', category: 'accessories' },
  { type: 'step-stool', name: 'Табурет-стремянка', width: 40, height: 35, color: '#F59E0B', icon: 'Square', category: 'accessories' },
  { type: 'fan-floor', name: 'Напольный вентилятор', width: 40, height: 40, color: '#E2E8F0', icon: 'Circle', category: 'accessories' },
  { type: 'heater', name: 'Обогреватель', width: 30, height: 50, color: '#DC2626', icon: 'RectangleHorizontal', category: 'accessories' },
  { type: 'humidifier', name: 'Увлажнитель', width: 25, height: 25, color: '#60A5FA', icon: 'Circle', category: 'accessories' },
  { type: 'air-purifier', name: 'Очиститель воздуха', width: 30, height: 30, color: '#F1F5F9', icon: 'Square', category: 'accessories' },
  { type: 'safe', name: 'Сейф', width: 40, height: 50, color: '#1E293B', icon: 'Square', category: 'accessories' },
  { type: 'vacuum', name: 'Пылесос', width: 30, height: 30, color: '#7C3AED', icon: 'Circle', category: 'accessories' },
  
  { type: 'tv-32', name: 'Телевизор 32"', width: 75, height: 10, color: '#1E293B', icon: 'RectangleHorizontal', category: 'electronics' },
  { type: 'tv-43', name: 'Телевизор 43"', width: 100, height: 10, color: '#1A1F2C', icon: 'RectangleHorizontal', category: 'electronics' },
  { type: 'tv-55', name: 'Телевизор 55"', width: 125, height: 10, color: '#0F172A', icon: 'RectangleHorizontal', category: 'electronics' },
  { type: 'tv-65', name: 'Телевизор 65"', width: 145, height: 10, color: '#020617', icon: 'RectangleHorizontal', category: 'electronics' },
  { type: 'monitor', name: 'Монитор', width: 50, height: 10, color: '#334155', icon: 'RectangleHorizontal', category: 'electronics' },
  { type: 'laptop', name: 'Ноутбук', width: 35, height: 25, color: '#64748B', icon: 'RectangleHorizontal', category: 'electronics' },
  { type: 'printer', name: 'Принтер', width: 45, height: 40, color: '#94A3B8', icon: 'RectangleHorizontal', category: 'electronics' },
  { type: 'speaker-floor', name: 'Напольная колонка', width: 30, height: 70, color: '#1E293B', icon: 'RectangleVertical', category: 'electronics' },
  { type: 'speaker-bookshelf', name: 'Полочная колонка', width: 20, height: 30, color: '#334155', icon: 'RectangleHorizontal', category: 'electronics' },
  { type: 'soundbar', name: 'Саундбар', width: 90, height: 10, color: '#1A1F2C', icon: 'RectangleHorizontal', category: 'electronics' },
  { type: 'subwoofer', name: 'Сабвуфер', width: 35, height: 35, color: '#0F172A', icon: 'Square', category: 'electronics' },
  { type: 'turntable', name: 'Проигрыватель', width: 45, height: 40, color: '#92400E', icon: 'Square', category: 'electronics' },
  { type: 'game-console', name: 'Игровая консоль', width: 30, height: 25, color: '#1E293B', icon: 'RectangleHorizontal', category: 'electronics' },
  
  { type: 'room-divider', name: 'Ширма', width: 150, height: 10, color: '#E5DEFF', icon: 'RectangleHorizontal', category: 'partitions' },
  { type: 'folding-screen', name: 'Складная ширма', width: 120, height: 10, color: '#D6BCFA', icon: 'RectangleHorizontal', category: 'partitions' },
  { type: 'bookshelf-divider', name: 'Стеллаж-перегородка', width: 120, height: 30, color: '#1A1F2C', icon: 'RectangleHorizontal', category: 'partitions' },
  { type: 'curtain-divider', name: 'Шторная перегородка', width: 100, height: 10, color: '#CBD5E1', icon: 'RectangleHorizontal', category: 'partitions' },
  
  { type: 'aquarium-small', name: 'Аквариум маленький', width: 60, height: 30, color: '#3B82F6', icon: 'RectangleHorizontal', category: 'pets' },
  { type: 'aquarium-large', name: 'Аквариум большой', width: 120, height: 50, color: '#2563EB', icon: 'RectangleHorizontal', category: 'pets' },
  { type: 'pet-bed', name: 'Лежанка для питомца', width: 70, height: 50, color: '#F87171', icon: 'RectangleHorizontal', category: 'pets' },
  { type: 'cat-tree', name: 'Игровой комплекс для кошек', width: 60, height: 60, color: '#92400E', icon: 'Square', category: 'pets' },
  { type: 'bird-cage', name: 'Клетка для птиц', width: 50, height: 50, color: '#FDE047', icon: 'Square', category: 'pets' },
];

export const furnitureCategories = [
  { id: 'living', name: 'Гостиная', icon: 'Sofa' },
  { id: 'bedroom', name: 'Спальня', icon: 'Bed' },
  { id: 'dining', name: 'Столовая', icon: 'Utensils' },
  { id: 'kitchen', name: 'Кухня', icon: 'ChefHat' },
  { id: 'office', name: 'Кабинет', icon: 'Briefcase' },
  { id: 'bathroom', name: 'Ванная', icon: 'Bath' },
  { id: 'decor', name: 'Декор', icon: 'Sparkles' },
  { id: 'sports', name: 'Спорт', icon: 'Dumbbell' },
  { id: 'entertainment', name: 'Развлечения', icon: 'Gamepad2' },
  { id: 'kids', name: 'Детская', icon: 'Baby' },
  { id: 'outdoor', name: 'Улица', icon: 'TreePine' },
  { id: 'laundry', name: 'Прачечная', icon: 'WashingMachine' },
  { id: 'storage', name: 'Хранение', icon: 'Archive' },
  { id: 'accessories', name: 'Аксессуары', icon: 'Package' },
  { id: 'electronics', name: 'Электроника', icon: 'Tv' },
  { id: 'partitions', name: 'Перегородки', icon: 'SeparatorVertical' },
  { id: 'pets', name: 'Для питомцев', icon: 'PawPrint' },
];

export const roomTemplates: RoomTemplate[] = [
  {
    id: 'living-room',
    name: 'Гостиная',
    description: 'Прямоугольная комната с окном и дверью',
    icon: 'Home',
    elements: [
      { type: 'wall-v', name: 'Стена', x: 50, y: 50, width: 10, height: 500, color: '#94A3B8', icon: 'RectangleVertical', isFixed: true },
      { type: 'wall-v', name: 'Стена', x: 690, y: 50, width: 10, height: 500, color: '#94A3B8', icon: 'RectangleVertical', isFixed: true },
      { type: 'wall-h', name: 'Стена', x: 50, y: 50, width: 650, height: 10, color: '#94A3B8', icon: 'RectangleHorizontal', isFixed: true },
      { type: 'wall-h', name: 'Стена', x: 50, y: 540, width: 650, height: 10, color: '#94A3B8', icon: 'RectangleHorizontal', isFixed: true },
      { type: 'window', name: 'Окно', x: 300, y: 50, width: 150, height: 10, color: '#60A5FA', icon: 'RectangleHorizontal', isFixed: true },
      { type: 'door', name: 'Дверь', x: 690, y: 250, width: 10, height: 80, color: '#92400E', icon: 'RectangleVertical', isFixed: true },
    ]
  },
  {
    id: 'bedroom',
    name: 'Спальня',
    description: 'Квадратная комната с окном',
    icon: 'Bed',
    elements: [
      { type: 'wall-v', name: 'Стена', x: 80, y: 80, width: 10, height: 440, color: '#94A3B8', icon: 'RectangleVertical', isFixed: true },
      { type: 'wall-v', name: 'Стена', x: 660, y: 80, width: 10, height: 440, color: '#94A3B8', icon: 'RectangleVertical', isFixed: true },
      { type: 'wall-h', name: 'Стена', x: 80, y: 80, width: 590, height: 10, color: '#94A3B8', icon: 'RectangleHorizontal', isFixed: true },
      { type: 'wall-h', name: 'Стена', x: 80, y: 510, width: 590, height: 10, color: '#94A3B8', icon: 'RectangleHorizontal', isFixed: true },
      { type: 'window', name: 'Окно', x: 280, y: 80, width: 180, height: 10, color: '#60A5FA', icon: 'RectangleHorizontal', isFixed: true },
      { type: 'door', name: 'Дверь', x: 660, y: 280, width: 10, height: 80, color: '#92400E', icon: 'RectangleVertical', isFixed: true },
    ]
  },
  {
    id: 'kitchen',
    name: 'Кухня',
    description: 'Узкая комната с окном и дверью',
    icon: 'ChefHat',
    elements: [
      { type: 'wall-v', name: 'Стена', x: 100, y: 100, width: 10, height: 400, color: '#94A3B8', icon: 'RectangleVertical', isFixed: true },
      { type: 'wall-v', name: 'Стена', x: 640, y: 100, width: 10, height: 400, color: '#94A3B8', icon: 'RectangleVertical', isFixed: true },
      { type: 'wall-h', name: 'Стена', x: 100, y: 100, width: 550, height: 10, color: '#94A3B8', icon: 'RectangleHorizontal', isFixed: true },
      { type: 'wall-h', name: 'Стена', x: 100, y: 490, width: 550, height: 10, color: '#94A3B8', icon: 'RectangleHorizontal', isFixed: true },
      { type: 'window', name: 'Окно', x: 250, y: 100, width: 140, height: 10, color: '#60A5FA', icon: 'RectangleHorizontal', isFixed: true },
      { type: 'door', name: 'Дверь', x: 100, y: 240, width: 10, height: 80, color: '#92400E', icon: 'RectangleVertical', isFixed: true },
    ]
  },
  {
    id: 'office',
    name: 'Кабинет',
    description: 'Комната с двумя окнами',
    icon: 'Briefcase',
    elements: [
      { type: 'wall-v', name: 'Стена', x: 70, y: 70, width: 10, height: 460, color: '#94A3B8', icon: 'RectangleVertical', isFixed: true },
      { type: 'wall-v', name: 'Стена', x: 670, y: 70, width: 10, height: 460, color: '#94A3B8', icon: 'RectangleVertical', isFixed: true },
      { type: 'wall-h', name: 'Стена', x: 70, y: 70, width: 610, height: 10, color: '#94A3B8', icon: 'RectangleHorizontal', isFixed: true },
      { type: 'wall-h', name: 'Стена', x: 70, y: 520, width: 610, height: 10, color: '#94A3B8', icon: 'RectangleHorizontal', isFixed: true },
      { type: 'window', name: 'Окно', x: 150, y: 70, width: 120, height: 10, color: '#60A5FA', icon: 'RectangleHorizontal', isFixed: true },
      { type: 'window', name: 'Окно', x: 480, y: 70, width: 120, height: 10, color: '#60A5FA', icon: 'RectangleHorizontal', isFixed: true },
      { type: 'door', name: 'Дверь', x: 70, y: 260, width: 10, height: 80, color: '#92400E', icon: 'RectangleVertical', isFixed: true },
    ]
  },
  {
    id: 'bathroom',
    name: 'Ванная',
    description: 'Маленькая комната с дверью',
    icon: 'Bath',
    elements: [
      { type: 'wall-v', name: 'Стена', x: 150, y: 120, width: 10, height: 360, color: '#94A3B8', icon: 'RectangleVertical', isFixed: true },
      { type: 'wall-v', name: 'Стена', x: 590, y: 120, width: 10, height: 360, color: '#94A3B8', icon: 'RectangleVertical', isFixed: true },
      { type: 'wall-h', name: 'Стена', x: 150, y: 120, width: 450, height: 10, color: '#94A3B8', icon: 'RectangleHorizontal', isFixed: true },
      { type: 'wall-h', name: 'Стена', x: 150, y: 470, width: 450, height: 10, color: '#94A3B8', icon: 'RectangleHorizontal', isFixed: true },
      { type: 'door', name: 'Дверь', x: 150, y: 260, width: 10, height: 80, color: '#92400E', icon: 'RectangleVertical', isFixed: true },
    ]
  },
  {
    id: 'dining-room',
    name: 'Столовая',
    description: 'Большая комната с двумя дверями',
    icon: 'UtensilsCrossed',
    elements: [
      { type: 'wall-v', name: 'Стена', x: 50, y: 50, width: 10, height: 500, color: '#94A3B8', icon: 'RectangleVertical', isFixed: true },
      { type: 'wall-v', name: 'Стена', x: 690, y: 50, width: 10, height: 500, color: '#94A3B8', icon: 'RectangleVertical', isFixed: true },
      { type: 'wall-h', name: 'Стена', x: 50, y: 50, width: 650, height: 10, color: '#94A3B8', icon: 'RectangleHorizontal', isFixed: true },
      { type: 'wall-h', name: 'Стена', x: 50, y: 540, width: 650, height: 10, color: '#94A3B8', icon: 'RectangleHorizontal', isFixed: true },
      { type: 'window', name: 'Окно', x: 270, y: 50, width: 200, height: 10, color: '#60A5FA', icon: 'RectangleHorizontal', isFixed: true },
      { type: 'door', name: 'Дверь', x: 50, y: 200, width: 10, height: 80, color: '#92400E', icon: 'RectangleVertical', isFixed: true },
      { type: 'door', name: 'Дверь', x: 690, y: 320, width: 10, height: 80, color: '#92400E', icon: 'RectangleVertical', isFixed: true },
    ]
  },
  {
    id: 'kids-room',
    name: 'Детская',
    description: 'Яркая комната с окном',
    icon: 'Baby',
    elements: [
      { type: 'wall-v', name: 'Стена', x: 80, y: 100, width: 10, height: 400, color: '#94A3B8', icon: 'RectangleVertical', isFixed: true },
      { type: 'wall-v', name: 'Стена', x: 660, y: 100, width: 10, height: 400, color: '#94A3B8', icon: 'RectangleVertical', isFixed: true },
      { type: 'wall-h', name: 'Стена', x: 80, y: 100, width: 590, height: 10, color: '#94A3B8', icon: 'RectangleHorizontal', isFixed: true },
      { type: 'wall-h', name: 'Стена', x: 80, y: 490, width: 590, height: 10, color: '#94A3B8', icon: 'RectangleHorizontal', isFixed: true },
      { type: 'window', name: 'Окно', x: 270, y: 100, width: 200, height: 10, color: '#60A5FA', icon: 'RectangleHorizontal', isFixed: true },
      { type: 'door', name: 'Дверь', x: 80, y: 260, width: 10, height: 80, color: '#92400E', icon: 'RectangleVertical', isFixed: true },
    ]
  },
  {
    id: 'walk-in-closet',
    name: 'Гардеробная',
    description: 'Узкая комната для одежды',
    icon: 'Shirt',
    elements: [
      { type: 'wall-v', name: 'Стена', x: 200, y: 150, width: 10, height: 300, color: '#94A3B8', icon: 'RectangleVertical', isFixed: true },
      { type: 'wall-v', name: 'Стена', x: 540, y: 150, width: 10, height: 300, color: '#94A3B8', icon: 'RectangleVertical', isFixed: true },
      { type: 'wall-h', name: 'Стена', x: 200, y: 150, width: 350, height: 10, color: '#94A3B8', icon: 'RectangleHorizontal', isFixed: true },
      { type: 'wall-h', name: 'Стена', x: 200, y: 440, width: 350, height: 10, color: '#94A3B8', icon: 'RectangleHorizontal', isFixed: true },
      { type: 'door', name: 'Дверь', x: 200, y: 260, width: 10, height: 80, color: '#92400E', icon: 'RectangleVertical', isFixed: true },
    ]
  },
  {
    id: 'laundry-room',
    name: 'Прачечная',
    description: 'Маленькая комната с дверью',
    icon: 'WashingMachine',
    elements: [
      { type: 'wall-v', name: 'Стена', x: 180, y: 140, width: 10, height: 320, color: '#94A3B8', icon: 'RectangleVertical', isFixed: true },
      { type: 'wall-v', name: 'Стена', x: 560, y: 140, width: 10, height: 320, color: '#94A3B8', icon: 'RectangleVertical', isFixed: true },
      { type: 'wall-h', name: 'Стена', x: 180, y: 140, width: 390, height: 10, color: '#94A3B8', icon: 'RectangleHorizontal', isFixed: true },
      { type: 'wall-h', name: 'Стена', x: 180, y: 450, width: 390, height: 10, color: '#94A3B8', icon: 'RectangleHorizontal', isFixed: true },
      { type: 'door', name: 'Дверь', x: 560, y: 260, width: 10, height: 80, color: '#92400E', icon: 'RectangleVertical', isFixed: true },
    ]
  },
  {
    id: 'home-gym',
    name: 'Домашний спортзал',
    description: 'Комната с большим окном',
    icon: 'Dumbbell',
    elements: [
      { type: 'wall-v', name: 'Стена', x: 60, y: 80, width: 10, height: 440, color: '#94A3B8', icon: 'RectangleVertical', isFixed: true },
      { type: 'wall-v', name: 'Стена', x: 680, y: 80, width: 10, height: 440, color: '#94A3B8', icon: 'RectangleVertical', isFixed: true },
      { type: 'wall-h', name: 'Стена', x: 60, y: 80, width: 630, height: 10, color: '#94A3B8', icon: 'RectangleHorizontal', isFixed: true },
      { type: 'wall-h', name: 'Стена', x: 60, y: 510, width: 630, height: 10, color: '#94A3B8', icon: 'RectangleHorizontal', isFixed: true },
      { type: 'window', name: 'Окно', x: 220, y: 80, width: 300, height: 10, color: '#60A5FA', icon: 'RectangleHorizontal', isFixed: true },
      { type: 'door', name: 'Дверь', x: 60, y: 270, width: 10, height: 80, color: '#92400E', icon: 'RectangleVertical', isFixed: true },
    ]
  },
  {
    id: 'library',
    name: 'Библиотека',
    description: 'Комната с тремя окнами',
    icon: 'BookOpen',
    elements: [
      { type: 'wall-v', name: 'Стена', x: 50, y: 60, width: 10, height: 480, color: '#94A3B8', icon: 'RectangleVertical', isFixed: true },
      { type: 'wall-v', name: 'Стена', x: 690, y: 60, width: 10, height: 480, color: '#94A3B8', icon: 'RectangleVertical', isFixed: true },
      { type: 'wall-h', name: 'Стена', x: 50, y: 60, width: 650, height: 10, color: '#94A3B8', icon: 'RectangleHorizontal', isFixed: true },
      { type: 'wall-h', name: 'Стена', x: 50, y: 530, width: 650, height: 10, color: '#94A3B8', icon: 'RectangleHorizontal', isFixed: true },
      { type: 'window', name: 'Окно', x: 120, y: 60, width: 120, height: 10, color: '#60A5FA', icon: 'RectangleHorizontal', isFixed: true },
      { type: 'window', name: 'Окно', x: 310, y: 60, width: 120, height: 10, color: '#60A5FA', icon: 'RectangleHorizontal', isFixed: true },
      { type: 'window', name: 'Окно', x: 500, y: 60, width: 120, height: 10, color: '#60A5FA', icon: 'RectangleHorizontal', isFixed: true },
      { type: 'door', name: 'Дверь', x: 50, y: 260, width: 10, height: 80, color: '#92400E', icon: 'RectangleVertical', isFixed: true },
    ]
  },
  {
    id: 'hallway',
    name: 'Прихожая',
    description: 'Длинный коридор',
    icon: 'DoorOpen',
    elements: [
      { type: 'wall-v', name: 'Стена', x: 250, y: 80, width: 10, height: 440, color: '#94A3B8', icon: 'RectangleVertical', isFixed: true },
      { type: 'wall-v', name: 'Стена', x: 490, y: 80, width: 10, height: 440, color: '#94A3B8', icon: 'RectangleVertical', isFixed: true },
      { type: 'wall-h', name: 'Стена', x: 250, y: 80, width: 250, height: 10, color: '#94A3B8', icon: 'RectangleHorizontal', isFixed: true },
      { type: 'wall-h', name: 'Стена', x: 250, y: 510, width: 250, height: 10, color: '#94A3B8', icon: 'RectangleHorizontal', isFixed: true },
      { type: 'door', name: 'Дверь', x: 250, y: 200, width: 10, height: 80, color: '#92400E', icon: 'RectangleVertical', isFixed: true },
      { type: 'door', name: 'Дверь', x: 490, y: 340, width: 10, height: 80, color: '#92400E', icon: 'RectangleVertical', isFixed: true },
    ]
  },
  {
    id: 'studio',
    name: 'Студия',
    description: 'Большое открытое пространство',
    icon: 'Sparkles',
    elements: [
      { type: 'wall-v', name: 'Стена', x: 40, y: 40, width: 10, height: 520, color: '#94A3B8', icon: 'RectangleVertical', isFixed: true },
      { type: 'wall-v', name: 'Стена', x: 700, y: 40, width: 10, height: 520, color: '#94A3B8', icon: 'RectangleVertical', isFixed: true },
      { type: 'wall-h', name: 'Стена', x: 40, y: 40, width: 670, height: 10, color: '#94A3B8', icon: 'RectangleHorizontal', isFixed: true },
      { type: 'wall-h', name: 'Стена', x: 40, y: 550, width: 670, height: 10, color: '#94A3B8', icon: 'RectangleHorizontal', isFixed: true },
      { type: 'window', name: 'Окно', x: 150, y: 40, width: 180, height: 10, color: '#60A5FA', icon: 'RectangleHorizontal', isFixed: true },
      { type: 'window', name: 'Окно', x: 410, y: 40, width: 180, height: 10, color: '#60A5FA', icon: 'RectangleHorizontal', isFixed: true },
      { type: 'door', name: 'Дверь', x: 700, y: 280, width: 10, height: 80, color: '#92400E', icon: 'RectangleVertical', isFixed: true },
    ]
  },
  {
    id: 'balcony',
    name: 'Балкон',
    description: 'Узкий балкон с перилами',
    icon: 'Fence',
    elements: [
      { type: 'wall-v', name: 'Стена', x: 220, y: 200, width: 10, height: 200, color: '#94A3B8', icon: 'RectangleVertical', isFixed: true },
      { type: 'wall-v', name: 'Стена', x: 520, y: 200, width: 10, height: 200, color: '#94A3B8', icon: 'RectangleVertical', isFixed: true },
      { type: 'wall-h', name: 'Перила', x: 220, y: 200, width: 310, height: 5, color: '#64748B', icon: 'RectangleHorizontal', isFixed: true },
      { type: 'wall-h', name: 'Стена', x: 220, y: 395, width: 310, height: 10, color: '#94A3B8', icon: 'RectangleHorizontal', isFixed: true },
      { type: 'door', name: 'Дверь', x: 335, y: 395, width: 80, height: 10, color: '#92400E', icon: 'RectangleHorizontal', isFixed: true },
    ]
  },
];